language: java
deploy:
  skip_cleanup: true
  provider: heroku
  app: spark-example-prodriguezmartinez
  api_key:
    secure: fzRDLC+Z/kUJTIvZuHSwmu1bd9HllcPsTbfPqtMEFMSGEYkxgLAfSPvR8Ss2KAL2z3e3agDFGhCNN96l/P6PskrPmcgnTdlDcX+E2Xn+RpR127CeLWlfjxyX9KkmaDCESwzoG9smYTzY2Sxj2oLpKJecg8C4/t4mutPUJJp/JFTT9FHcBeXklqLhqqQ8XWMkTwJbVMd7sGSFE4trBSh0QpWO5vqe1zZ+4mzh7QII0KZmqzqA91lPfKY0QLpnrIpS+AEB4yqekYmGHvfTB6FXU+Rwj964h9Qh/Cu7TnIqmnDB8T9z3boH1K8xuHppUjaaeFrI7Af9P2w1AWrbpw/bIriKPVRqPrOaVpRhxzt5N/4DOctIijeGjXD7IWOOrIQMDUqOsYGoPryTTSQZ8Lxyae82yP1Urhzawf8IwEH+egxgchjnlrHPhOgOh/ot0f5Bnmxe4PpUglVdZeyzBrQS9sq82Yh+Q0TRD/pcdCj5vXluq0SciH7A/vg5sXGqvYEQjAL2qey8Wu/U2XnWkNLm91IHqL9rKAQ6jlsqLRto3GwSlM8xHu44+u/p578C05IejeJdwfIuVSNRwnjCI+cKYkc/2TDsmJFdVfbuQy07kmkaVRP/QIojslAiX4FuXoze5h3cWbxIWLiV88FqM497iGaGTImYUkAzdnwflGCj2QU=
